### ISSUE TITLE
Date sorting does not work in the three tabs 'Today's Appointments','Future Appointments' and 'Appoinments Pending Approval' 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#18] opened 2014-04-09 11:32 UTC
## Steps to reproduce
1. Login into DGC with HCP Login
2. Click HCP dropdown on the top left of the header
3. Click 'My Appointments'
4. Click on 'Today's Appointments' tab and click on 'Date' sorting
5. Click on 'Future Appointments' tab and click on 'Date' sorting
6. Click on 'Appoinments Pending Approval' tab and click on 'Date' sorting
## Actual Result

Sorts the date only but does not validate the month
Eg: The values are sorted as below
07 March
15 May
17 June
30 March
## Expected Result

The date should be sorted along with the month
Eg: The values should be sorted as below
07 March
30 March
15 May
17 June

**Comment by shanthasprim** [comment] 2014-04-10 07:04
##  Precondition: 

Appointments should be added under all the three tabs  'Today's Appointments','Future Appointments' and 'Appoinments Pending Approval'

**Comment by vijayhegde1** [comment] 2015-03-03 05:45
Working as expected, unable to reproduce

**Comment by shanthasprim** [comment] 2015-03-17 10:16
Working as Expected. Hence closing the issue.

**Closed as completed by shanthasprim** 2015-03-17 10:16 UTC
Labels: bug, HCP, Fixed, Appointments
